"""empty message

Revision ID: 142a8e8b47da
Revises: 92a74647a981
Create Date: 2019-09-04 02:05:11.720021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142a8e8b47da'
down_revision = '92a74647a981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collectors')
    # ### end Alembic commands ###
