"""empty message

Revision ID: 1bfde2e7bcdd
Revises: 142a8e8b47da
Create Date: 2019-09-05 23:53:34.941413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfde2e7bcdd'
down_revision = '142a8e8b47da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collectors_owner_id_key', 'collectors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('collectors_owner_id_key', 'collectors', ['owner_id'])
    # ### end Alembic commands ###
